import {
  type AgentD1Database,
  createAgentRepository,
  runScheduledAgentTick,
} from "@knoww/agent";
import { createLogger } from "@knoww/logger";
// Generated by `opennextjs-cloudflare build`; absent during source-only TS
// checks, so keep this import boundary explicitly acknowledged.
// @ts-expect-error OpenNext emits this module at build time.
import { default as openNextWorker } from "./.open-next/worker.js";

const log = createLogger("agent.cron");

interface AgentWorkerEnv extends CloudflareEnv {
  AGENT_DB: D1Database;
  AGENT_CRON_ENABLED?: string;
  AGENT_CRON_EXECUTION_MODE?: string;
  AGENT_CRON_LOCK_LEASE_MS?: string;
}

export default {
  fetch: openNextWorker.fetch,

  async scheduled(
    controller: ScheduledController,
    env: AgentWorkerEnv,
    ctx: ExecutionContext
  ) {
    ctx.waitUntil(
      (async () => {
        const repository = createAgentRepository(
          env.AGENT_DB as AgentD1Database | undefined
        );
        const result = await runScheduledAgentTick(repository, {
          env: {
            AGENT_CRON_ENABLED: env.AGENT_CRON_ENABLED,
            AGENT_CRON_EXECUTION_MODE: env.AGENT_CRON_EXECUTION_MODE,
            AGENT_CRON_LOCK_LEASE_MS: env.AGENT_CRON_LOCK_LEASE_MS,
          },
        });
        log.info("tick.finished", {
          cron: controller.cron,
          scheduledTime: new Date(controller.scheduledTime).toISOString(),
          ...result,
        });
      })()
    );
  },
} satisfies ExportedHandler<AgentWorkerEnv>;
