import Image from "next/image";
import { cn } from "@/lib/utils";

/**
 * Editorial K-mark — the platform's primary brand mark. Renders the
 * diamond-cutout K logo as a raster image so the live UI matches the
 * favicon and OG assets exactly. Source PNG is regenerated by
 * `pnpm brand:render` from `tooling/brand/knoww-k-mark.png`.
 *
 * Reach for this anywhere the prior text-K block was used as a small
 * inline brand cue. Don't use it for favicons or OG images — those
 * already get rendered raster files of their own.
 */
export interface KnowwMarkProps {
  /** Visual size of the mark. `md` is the default and matches the nav. */
  size?: "sm" | "md" | "lg";
  /** Extra classes — useful for spacing tweaks at the call site. */
  className?: string;
}

const SIZES = {
  sm: 20,
  md: 24,
  lg: 40,
} as const;

export function KnowwMark({ size = "md", className }: KnowwMarkProps) {
  const px = SIZES[size];
  return (
    <Image
      src="/logo-256x256.png"
      alt="Knoww"
      width={px}
      height={px}
      className={cn("inline-block shrink-0 select-none", className)}
      priority
      unoptimized
    />
  );
}
