/**
 * Re-export shared contract constants.
 * All contract addresses are defined in @knoww/shared-types.
 */
export {
  COLLATERAL_ONRAMP_ADDRESS,
  CONTRACTS,
  CTF_ADDRESS,
  CTF_APPROVAL_OPERATORS,
  CTF_COLLATERAL_ADAPTER_ADDRESS,
  CTF_EXCHANGE_ADDRESS,
  DEPOSIT_WALLET_BEACON_ADDRESS,
  DEPOSIT_WALLET_FACTORY_ADDRESS,
  NEG_RISK_CTF_COLLATERAL_ADAPTER_ADDRESS,
  NEG_RISK_CTF_EXCHANGE_ADDRESS,
  PUSD_ADDRESS,
  PUSD_APPROVAL_TARGETS,
  PUSD_CTF_APPROVAL_TARGET,
  PUSD_DECIMALS,
  SAFE_FACTORY_ADDRESS,
  SAFE_INIT_CODE_HASH,
  USDC_E_ADDRESS,
  USDC_E_DECIMALS,
  USDC_E_ONRAMP_APPROVAL_TARGET,
} from "@knoww/shared-types/contracts";
