import { createLogger } from "@knoww/logger";
import {
  buildClobL1Headers,
  createOrDeriveClobApiKey,
} from "@knoww/shared-types/polymarket";
import { type NextRequest, NextResponse } from "next/server";
import { getAddress } from "viem";
import { z } from "zod";
import { CLOB_BASE_URL } from "@/constants/polymarket";
import { checkRateLimit } from "@/lib/api-rate-limit";
import { readJsonBodyWithLimit } from "@/lib/api-request-body";
import {
  getPostHogClient,
  isPostHogServerConfigured,
} from "@/lib/posthog-server";
import { isValidAddress } from "@/lib/validation";

const log = createLogger("api.auth.derive-api-key");
const MAX_REQUEST_BODY_BYTES = 8 * 1024;

/**
 * Schema for L1 authentication headers
 * These are generated by signing an EIP-712 message on the frontend
 */
const l1AuthSchema = z.object({
  address: z
    .string()
    .describe("User's Polygon address")
    .refine(isValidAddress, { message: "Invalid Ethereum address format" }),
  signature: z.string().describe("EIP-712 signature"),
  timestamp: z.string().describe("UNIX timestamp used in signature"),
  nonce: z.string().optional().default("0").describe("Nonce used in signature"),
});

function trackApiKeyEvent(
  address: string,
  event: string,
  method: string,
  hostname: string
): void {
  if (!isPostHogServerConfigured()) return;
  try {
    const posthog = getPostHogClient();
    posthog.capture({
      distinctId: getAddress(address),
      event,
      properties: {
        product: "web",
        analytics_version: 2,
        environment: ["knoww.app", "www.knoww.app"].includes(hostname)
          ? "production"
          : "development",
        wallet_address: getAddress(address),
        method,
      },
    });
    posthog.flush().catch(() => {});
  } catch {
    // Analytics must never affect the API response
  }
}

/**
 * POST /api/auth/derive-api-key
 *
 * Create or derive API key credentials for a user using their L1 authentication.
 * This endpoint implements the "createOrDeriveApiKey" pattern:
 *
 * 1. First, try to DERIVE an existing API key (for returning users)
 * 2. If derivation fails, CREATE a new API key (for first-time users)
 *
 * This ensures:
 * - New users get their API key created
 * - Returning users get their existing API key derived
 *
 * Flow:
 * 1. Frontend signs EIP-712 ClobAuth message
 * 2. Frontend sends signature + metadata to this endpoint
 * 3. Backend tries GET /auth/derive-api-key (derive)
 * 4. If fails, backend tries POST /auth/api-key (create)
 * 5. Backend returns the API credentials to frontend
 * 6. Frontend stores credentials for future order submissions
 */
/**
 * @openapi
 * /api/auth/derive-api-key:
 *   post:
 *     summary: Create or proxy /api/auth/derive-api-key.
 *     tags: [Auth]
 *     responses:
 *       200:
 *         description: Successful response.
 *       400:
 *         description: Invalid request.
 *       401:
 *         description: Authentication required.
 *       403:
 *         description: Request forbidden.
 *       404:
 *         description: Resource not found.
 *       429:
 *         description: Rate limit exceeded.
 *       500:
 *         description: Request failed.
 */
export async function POST(request: NextRequest) {
  // Rate limit: 10 requests per minute (auth is sensitive)
  const rateLimitResponse = checkRateLimit(request, {
    uniqueTokenPerInterval: 10,
  });
  if (rateLimitResponse) return rateLimitResponse;

  try {
    const jsonBody = await readJsonBodyWithLimit(
      request,
      MAX_REQUEST_BODY_BYTES
    );
    if (!jsonBody.ok) {
      return NextResponse.json(
        {
          success: false,
          error: jsonBody.error,
        },
        { status: jsonBody.status }
      );
    }

    const parsed = l1AuthSchema.safeParse(jsonBody.body);

    if (!parsed.success) {
      return NextResponse.json(
        {
          success: false,
          error: "Invalid request body",
        },
        { status: 400 }
      );
    }

    const { address, signature, timestamp, nonce } = parsed.data;

    const clobHost = CLOB_BASE_URL;

    const result = await createOrDeriveClobApiKey(
      clobHost,
      buildClobL1Headers({ address, signature, timestamp, nonce })
    );

    if (result.success && result.data && result.method) {
      trackApiKeyEvent(
        address,
        result.method === "derive"
          ? "trading_api_key_derived"
          : "trading_api_key_created",
        result.method,
        request.nextUrl.hostname
      );
      return NextResponse.json({
        success: true,
        credentials: result.data,
        method: result.method,
      });
    }

    // Both create and derive failed. Log only the failure-class flags —
    // raw upstream credential-flow error strings may contain signed headers
    // or credential-derivation internals.
    log.error("auth.both_failed", {
      hasCreateError: Boolean(result.createError),
      hasDeriveError: Boolean(result.deriveError),
    });

    // Provide helpful error message
    let errorMessage = "Failed to create or retrieve API credentials.";

    if (
      result.createError?.includes("not enabled") ||
      result.deriveError?.includes("not enabled")
    ) {
      errorMessage =
        "Your wallet is not enabled for trading. Please complete the wallet setup steps first (Deploy wallet & Approve trading tokens).";
    } else if (
      result.createError?.includes("signature") ||
      result.deriveError?.includes("signature")
    ) {
      errorMessage = "Signature verification failed. Please try signing again.";
    }

    return NextResponse.json(
      {
        success: false,
        error: errorMessage,
      },
      { status: 400 }
    );
  } catch (error) {
    log.error("request.failed", { error });
    return NextResponse.json(
      {
        success: false,
        error: "Failed to create or retrieve API credentials.",
      },
      { status: 500 }
    );
  }
}
